name: Sync
version: '%VERSION%'
main: dev.heliosares.sync.spigot.SyncSpigot
description: Sync
api-version: 1.13
author: Heliosares
softdepend: [PremiumVanish, PlaceholderAPI]

commands:
    psync:
        usage: /psync
        description: Base command
    if:
        usage: /if
        description: Base command
    mtell:
        usage: /mtell <player> <msg>
        description: Send a player a message on any server